import house from "./house.png.asset.json";
import videoGame from "./video_game.png.asset.json";
import heartWithArrow from "./heart_with_arrow.png.asset.json";
import cameraWithFlash from "./camera_with_flash.png.asset.json";
import gear from "./gear.png.asset.json";
import loveLetter from "./love_letter.png.asset.json";
import sparkles from "./sparkles.png.asset.json";
import faceHearts from "./smiling_face_with_hearts.png.asset.json";
import faceSmile from "./smiling_face_with_smiling_eyes.png.asset.json";
import redHeart from "./red_heart.png.asset.json";
export const emoji = { house, videoGame, heartWithArrow, cameraWithFlash, gear, loveLetter, sparkles, faceHearts, faceSmile, redHeart };
