import { useState, type ReactNode, type ComponentProps } from "react";
import { motion, AnimatePresence, useReducedMotion } from "motion/react";
import * as Dialog from "@radix-ui/react-dialog";
import { useTranslation } from "react-i18next";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { FlameMascot } from "./FlameMascot";
import { emoji } from "@/assets/emoji";

const MotionButton = motion.create(Button);
const press = { scale: 0.95 };
type VisualButtonProps = ComponentProps<typeof MotionButton>;
export function PrimaryButton({ className, children, ...props }: VisualButtonProps) { return <MotionButton whileTap={press} transition={{ type: "spring", stiffness: 430, damping: 23 }} className={cn("h-[52px] w-full rounded-full bg-primary px-7 text-base font-extrabold text-primary-foreground shadow-ember hover:bg-primary/90 focus-visible:ring-2 focus-visible:ring-ring", className)} {...props}>{children}</MotionButton>; }
export function SecondaryButton({ className, children, ...props }: VisualButtonProps) { return <MotionButton whileTap={press} transition={{ type: "spring", stiffness: 430, damping: 23 }} className={cn("h-[52px] w-full rounded-full bg-secondary px-7 text-base font-extrabold text-secondary-foreground shadow-soft hover:bg-secondary/80 focus-visible:ring-2 focus-visible:ring-ring", className)} {...props}>{children}</MotionButton>; }
export function PillTag({ children, className }: { children: ReactNode; className?: string }) { return <span className={cn("inline-flex w-fit items-center rounded-full bg-tag px-4 py-2 text-[11px] font-black uppercase text-tag-foreground", className)}>{children}</span>; }
export function BigCard({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn("rounded-[28px] bg-card p-6 text-card-foreground shadow-card", className)}>{children}</div>; }
export type GradientName = "memory" | "food" | "tet" | "distance" | "deep" | "fun";
export const gradients: GradientName[] = ["memory", "food", "tet", "distance", "deep", "fun"];
export function GradientScreen({ gradient, children, className }: { gradient: GradientName; children: ReactNode; className?: string }) { return <div className={cn("gradient-screen flex min-h-[380px] flex-col justify-between overflow-hidden rounded-[30px] p-6 text-gradient-foreground", `gradient-${gradient}`, className)}>{children}</div>; }
export function BottomSheet({ open, onOpenChange, children }: { open: boolean; onOpenChange: (open: boolean) => void; children: ReactNode }) { const { t } = useTranslation(); return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-overlay data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=open]:fade-in-0 data-[state=closed]:fade-out-0"/><Dialog.Content className="fixed inset-x-0 bottom-0 z-50 mx-auto max-w-[390px] rounded-t-[32px] bg-card px-6 pb-10 pt-4 text-card-foreground shadow-sheet outline-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=open]:slide-in-from-bottom data-[state=closed]:slide-out-to-bottom"><div className="mx-auto mb-7 h-1.5 w-12 rounded-full bg-muted"/><Dialog.Title className="sr-only">{t("sheet.title")}</Dialog.Title><Dialog.Description className="sr-only">{t("sheet.body")}</Dialog.Description>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>; }
export function AvatarPair({ firstDone = true, secondDone = false }: { firstDone?: boolean; secondDone?: boolean }) { const { t } = useTranslation(); return <div className="flex items-center gap-4"><div className="flex -space-x-4"><div className={cn("relative grid size-16 place-items-center rounded-full bg-avatar-one text-3xl shadow-soft ring-4 ring-background", firstDone && "avatar-done")} role="img" aria-label={`${t("avatars.you")}: ${t(firstDone ? "avatars.done" : "avatars.waiting")}`}><img src={emoji.faceHearts.url} alt="" className="size-11 object-contain"/><span className="avatar-status">{firstDone ? "✓" : "·"}</span></div><div className={cn("relative grid size-16 place-items-center rounded-full bg-avatar-two text-3xl shadow-soft ring-4 ring-background", secondDone && "avatar-done")} role="img" aria-label={`${t("avatars.partner")}: ${t(secondDone ? "avatars.done" : "avatars.waiting")}`}><img src={emoji.faceSmile.url} alt="" className="size-11 object-contain"/><span className="avatar-status">{secondDone ? "✓" : "·"}</span></div></div><div className="flex flex-col gap-1 text-sm font-bold text-foreground"><span>{t("avatars.you")} · {t(firstDone ? "avatars.done" : "avatars.waiting")}</span><span className="text-muted-foreground">{t("avatars.partner")} · {t(secondDone ? "avatars.done" : "avatars.waiting")}</span></div></div>; }
export function FlameStreak({ count = 7, size = "large" }: { count?: number; size?: "small" | "medium" | "large" }) { const { t } = useTranslation(); return <div className={cn("inline-flex items-center gap-2 rounded-full bg-streak px-4 py-2 text-streak-foreground shadow-soft", size === "large" && "gap-3 px-5 py-3", size === "small" && "px-3 py-1 text-sm")}><FlameMascot expression="mung" size={size === "large" ? 42 : size === "medium" ? 30 : 23} pulse/><span className={cn("font-black", size === "large" && "text-xl")}>{count}</span><span className="font-bold">{t("streak.label")}</span></div>; }
export function EmptyState() { const { t } = useTranslation(); return <div className="flex min-h-[240px] flex-col items-center justify-center gap-4 text-center"><FlameMascot expression="nho" size={114} pulse/><p className="max-w-[250px] text-lg font-bold leading-snug text-foreground">{t("empty")}</p></div>; }
const bits = Array.from({ length: 18 }, (_, i) => ({ x: ((i * 71) % 240) - 120, y: -((i * 43) % 160) - 28, rotate: i * 37, delay: (i % 5) * 0.045 }));
export function Confetti({ active }: { active: boolean }) { const reduce = useReducedMotion(); return <div aria-hidden="true" className="pointer-events-none absolute inset-0 z-10 overflow-hidden"><AnimatePresence>{active && !reduce && bits.map((bit, i) => <motion.span key={i} className={cn("absolute left-1/2 top-1/2 size-2.5 rounded-[3px]", ["bg-primary", "bg-rose", "bg-gold", "bg-mint"][i % 4])} initial={{ x: 0, y: 0, opacity: 1, rotate: 0, scale: 0 }} animate={{ x: bit.x, y: bit.y, opacity: 0, rotate: bit.rotate, scale: 1 }} exit={{ opacity: 0 }} transition={{ duration: 1.15, delay: bit.delay, ease: "easeOut" }}/>)}</AnimatePresence></div>; }
export function SwipeCard({ onSwipe }: { onSwipe?: (direction: "left" | "right") => void }) { const { t } = useTranslation(); const [key, setKey] = useState(0); return <motion.div key={key} drag="x" dragConstraints={{ left: 0, right: 0 }} dragElastic={0.9} whileDrag={{ scale: 1.035 }} onDragEnd={(_, info) => { if (Math.abs(info.offset.x) > 70 || Math.abs(info.velocity.x) > 450) { onSwipe?.(info.offset.x < 0 ? "left" : "right"); setKey((value) => value + 1); } }} initial={{ opacity: 0, y: 20, scale: 0.96 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ type: "spring", stiffness: 300, damping: 23 }} className="touch-pan-y cursor-grab select-none rounded-[28px] bg-card p-6 shadow-card active:cursor-grabbing" aria-label={t("swipeLabel")}><PillTag>{t("card.tag")}</PillTag><h3 className="mt-7 text-[26px] font-black leading-tight text-foreground">{t("card.title")}</h3><p className="mt-3 text-base leading-relaxed text-muted-foreground">{t("card.body")}</p><div className="mt-8 flex justify-between text-2xl"><img src={emoji.loveLetter.url} alt="" className="size-9 object-contain"/><img src={emoji.sparkles.url} alt="" className="size-9 object-contain"/></div></motion.div>; }
export const tabs = [{ key: "home", icon: emoji.house.url }, { key: "play", icon: emoji.videoGame.url }, { key: "date", icon: emoji.heartWithArrow.url }, { key: "memories", icon: emoji.cameraWithFlash.url }, { key: "settings", icon: emoji.gear.url }] as const;
export function BottomTabBar({ active = "home", onSelect }: { active?: typeof tabs[number]["key"]; onSelect?: (tab: typeof tabs[number]["key"]) => void }) { const { t } = useTranslation(); return <nav aria-label={t("navigationLabel")} className="flex h-[76px] items-center justify-around rounded-[28px] bg-nav px-2 shadow-nav">{tabs.map((tab) => <MotionButton key={tab.key} variant="ghost" size="icon" whileTap={press} aria-label={t(`tabs.${tab.key}`)} aria-current={active === tab.key ? "page" : undefined} onClick={() => onSelect?.(tab.key)} className={cn("flex h-[62px] w-[62px] flex-col gap-0 rounded-[21px] p-1 text-nav-foreground hover:bg-nav-active hover:text-nav-foreground [&_svg]:size-auto", active === tab.key && "bg-nav-active text-primary hover:text-primary")}><img src={tab.icon} alt="" className="size-[29px] object-contain"/><span className="text-[10px] font-extrabold leading-4">{t(`tabs.${tab.key}`)}</span></MotionButton>)}</nav>; }
