/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as JoinRouteImport } from './routes/join'
import { Route as PreviewHomeRouteImport } from './routes/preview-home'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPairRouteImport } from './routes/_authenticated/pair'
import { Route as AuthenticatedPhotoRouteImport } from './routes/_authenticated/photo'
import { Route as AuthenticatedQuestionRouteImport } from './routes/_authenticated/question'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewHomeRoute = PreviewHomeRouteImport.update({
  id: '/preview-home',
  path: '/preview-home',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPairRoute = AuthenticatedPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPhotoRoute = AuthenticatedPhotoRouteImport.update({
  id: '/photo',
  path: '/photo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestionRoute = AuthenticatedQuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/intro': typeof IntroRoute
  '/join': typeof JoinRoute
  '/preview-home': typeof PreviewHomeRoute
  '/privacy': typeof PrivacyRoute
  '/styleguide': typeof StyleguideRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pair': typeof AuthenticatedPairRoute
  '/photo': typeof AuthenticatedPhotoRoute
  '/question': typeof AuthenticatedQuestionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/intro': typeof IntroRoute
  '/join': typeof JoinRoute
  '/preview-home': typeof PreviewHomeRoute
  '/privacy': typeof PrivacyRoute
  '/styleguide': typeof StyleguideRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pair': typeof AuthenticatedPairRoute
  '/photo': typeof AuthenticatedPhotoRoute
  '/question': typeof AuthenticatedQuestionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/intro': typeof IntroRoute
  '/join': typeof JoinRoute
  '/preview-home': typeof PreviewHomeRoute
  '/privacy': typeof PrivacyRoute
  '/styleguide': typeof StyleguideRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pair': typeof AuthenticatedPairRoute
  '/_authenticated/photo': typeof AuthenticatedPhotoRoute
  '/_authenticated/question': typeof AuthenticatedQuestionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/demo'
    | '/intro'
    | '/join'
    | '/preview-home'
    | '/privacy'
    | '/styleguide'
    | '/terms'
    | '/app'
    | '/onboarding'
    | '/pair'
    | '/photo'
    | '/question'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/demo'
    | '/intro'
    | '/join'
    | '/preview-home'
    | '/privacy'
    | '/styleguide'
    | '/terms'
    | '/app'
    | '/onboarding'
    | '/pair'
    | '/photo'
    | '/question'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/demo'
    | '/intro'
    | '/join'
    | '/preview-home'
    | '/privacy'
    | '/styleguide'
    | '/terms'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/pair'
    | '/_authenticated/photo'
    | '/_authenticated/question'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  IntroRoute: typeof IntroRoute
  JoinRoute: typeof JoinRoute
  PreviewHomeRoute: typeof PreviewHomeRoute
  PrivacyRoute: typeof PrivacyRoute
  StyleguideRoute: typeof StyleguideRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-home': {
      id: '/preview-home'
      path: '/preview-home'
      fullPath: '/preview-home'
      preLoaderRoute: typeof PreviewHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pair': {
      id: '/_authenticated/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof AuthenticatedPairRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/photo': {
      id: '/_authenticated/photo'
      path: '/photo'
      fullPath: '/photo'
      preLoaderRoute: typeof AuthenticatedPhotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/question': {
      id: '/_authenticated/question'
      path: '/question'
      fullPath: '/question'
      preLoaderRoute: typeof AuthenticatedQuestionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPairRoute: typeof AuthenticatedPairRoute
  AuthenticatedPhotoRoute: typeof AuthenticatedPhotoRoute
  AuthenticatedQuestionRoute: typeof AuthenticatedQuestionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPairRoute: AuthenticatedPairRoute,
  AuthenticatedPhotoRoute: AuthenticatedPhotoRoute,
  AuthenticatedQuestionRoute: AuthenticatedQuestionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  IntroRoute: IntroRoute,
  JoinRoute: JoinRoute,
  PreviewHomeRoute: PreviewHomeRoute,
  PrivacyRoute: PrivacyRoute,
  StyleguideRoute: StyleguideRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
